apiVersion: apps/v1
kind: Deployment
metadata:
  name: retry-tester-client
  labels:
    app: retry-tester
    component: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retry-tester
      component: client
  template:
    metadata:
      labels:
        app: retry-tester
        component: client
    spec:
      containers:
      - name: client
        image: eu.gcr.io/infra-sandbox-58fe57e9/grpc-tester:latest
        command: ["/client", "-address", "retry-tester"]
