---
name: destination-tester
namespace: service-discovery
default_connection_config:
  protocol: HTTP2
  traffic_topology: NO_AFFINITY
  active_health_check:
    grpc:
      service: "failedHC-checker"
default_route_config:
  request_timeout: "0.500s"
endpointGroups:
  default:
    weight: 100
    selector:
      kubernetesServiceSelector:
        name: destination-tester
        namespace: service-discovery
        port: 50051
