apiVersion: v1
kind: Service
metadata:
  annotations:
    datadoghq.com/fabric-platform-dns: enable
  labels:
    service: destination-tester
    component: server
  name: destination-tester
  namespace: service-discovery
spec:
  clusterIP: None
  ports:
  - name: http-admin
    port: 8888
    protocol: TCP
  - name: grpc
    port: 50051
    protocol: TCP
  selector:
    service: destination-tester
    component: server
